# vCD
- application: vCD
  host: 192.168.2.101
  user: admin
  password: vmware1!
# vCenter
- application: vCenter
  host: 192.168.2.100
  user: Administrator
  password: vmware1!
# ESX
- application: ESX
  user: root
  password: vmware1!
# Chargeback DB
- application: VCBDB
  host: 192.168.2.101
  database: orclXDB
  user: vcb
  password: VMware123

  
