# vCD
- application: vCD
  host: 10.149.64.18
  user: admin
  password: vmware1!
# vCenter
- application: vCenter
  host: 10.149.64.6
  user: Administrator
  password: vmware1!
# ESX
- application: ESX
  user: root
  password: vmware1!
# Chargeback DB
- application: VCBDB
  host: 10.149.64.18
  database: orclXDB
  user: vcb
  password: VMware123

  
